CREATE ROLE DIRETTORE;
GRANT CONNECT TO DIRETTORE;
GRANT SELECT, INSERT, DELETE, UPDATE ON TESINA_DBA.ATTORI TO DIRETTORE;
GRANT SELECT, INSERT, DELETE, UPDATE ON TESINA_DBA.FILM TO DIRETTORE;
GRANT SELECT, INSERT, DELETE, UPDATE ON TESINA_DBA.REGIE TO DIRETTORE;
GRANT SELECT, INSERT, DELETE, UPDATE ON TESINA_DBA.SALE TO DIRETTORE;
GRANT SELECT, INSERT, DELETE, UPDATE ON TESINA_DBA.PALINSESTI TO DIRETTORE;
GRANT SELECT, INSERT, DELETE, UPDATE ON TESINA_DBA.UTENTI TO DIRETTORE;
GRANT SELECT, INSERT, DELETE, UPDATE ON TESINA_DBA.DIREZIONI TO DIRETTORE;
GRANT SELECT, INSERT, DELETE, UPDATE ON TESINA_DBA.POSTI TO DIRETTORE;
GRANT SELECT, INSERT, DELETE, UPDATE ON TESINA_DBA.PRENOTAZIONI TO DIRETTORE;
GRANT SELECT, INSERT, DELETE, UPDATE ON TESINA_DBA.RECITAZIONI TO DIRETTORE;

CREATE ROLE PROGRAMMAZIONE;
GRANT CONNECT TO PROGRAMMAZIONE;
GRANT SELECT, INSERT, DELETE, UPDATE ON TESINA_DBA.FILM TO PROGRAMMAZIONE;
GRANT SELECT, INSERT, DELETE, UPDATE ON TESINA_DBA.PALINSESTI TO PROGRAMMAZIONE;

CREATE ROLE LOCANDINE;
GRANT CONNECT TO LOCANDINE;
GRANT SELECT, INSERT, DELETE, UPDATE ON TESINA_DBA.FILM TO LOCANDINE;

CREATE ROLE BOTTEGHINO;
GRANT CONNECT TO BOTTEGHINO;
GRANT SELECT, INSERT, DELETE, UPDATE ON TESINA_DBA.FILM TO BOTTEGHINO;

CREATE ROLE UTENTE;
GRANT CONNECT TO UTENTE;
GRANT SELECT ON TESINA_DBA.PALINSESTI TO UTENTE;
GRANT INSERT ON TESINA_DBA.PRENOTAZIONI TO UTENTE;
GRANT INSERT ON TESINA_DBA.POSTI TO UTENTE;