CREATE TABLE SOCIETA(
	CANTONE VARCHAR2(16) PRIMARY KEY,
	NOME VARCHAR2(50));

CREATE TABLE CINEMA(
	NOME VARCHAR2(50),
	CITTA VARCHAR2(50),
	INDIRIZZO VARCHAR2(50),
	RECAPITO NUMBER(10),
	NUMEROSALE NUMBER(2) NOT NULL,
	CANTONE VARCHAR2(16),
	PRIMARY KEY (NOME, CITTA),
	FOREIGN KEY (CANTONE) REFERENCES SOCIETA (CANTONE));

CREATE TABLE SALE(
	NOME VARCHAR2(50),
	CITTA VARCHAR2(50),
	SUPERFICIE NUMBER(3) NOT NULL,
	CAPIENZA NUMBER(3) NOT NULL,
	NUMERO NUMBER(2),
	PRIMARY KEY (NOME, CITTA, NUMERO),
	FOREIGN KEY (NOME, CITTA) REFERENCES CINEMA (NOME, CITTA));

CREATE TABLE FILM(
	TITOLO VARCHAR2(50) PRIMARY KEY,
	GENERE VARCHAR2(50),
	DURATA VARCHAR2(3));

CREATE TABLE PALINSESTI(
	GIORNO DATE,
	ORARIO CHAR(5),
	NUMERO NUMBER(2),
	NOME VARCHAR2(50),
	CITTA VARCHAR2(50),
	PREZZO NUMBER(5) DEFAULT NULL,
	TITOLO VARCHAR2(50),
	PRIMARY KEY (GIORNO, ORARIO, NUMERO, NOME, CITTA),
	FOREIGN KEY (NUMERO, NOME, CITTA) REFERENCES SALE (NUMERO, NOME, CITTA),
	FOREIGN KEY (TITOLO) REFERENCES FILM (TITOLO));

CREATE TABLE ATTORI(
	NOME VARCHAR2(50),
	COGNOME VARCHAR2(50),
	ID CHAR(5) PRIMARY KEY);

CREATE TABLE REGIE(
	NOME VARCHAR2(50),
	COGNOME VARCHAR2(50),
	ID CHAR(5) PRIMARY KEY);

CREATE TABLE RECITAZIONI(
	TITOLO VARCHAR2(50),
	ID CHAR(5),
	PRIMARY KEY (TITOLO, ID),
	FOREIGN KEY (TITOLO) REFERENCES FILM (TITOLO),
	FOREIGN KEY (ID) REFERENCES ATTORI (ID));

CREATE TABLE DIREZIONI(
	TITOLO VARCHAR2(50) PRIMARY KEY,
	ID CHAR(5),
	FOREIGN KEY (TITOLO) REFERENCES FILM (TITOLO),
	FOREIGN KEY (ID) REFERENCES REGIE (ID));

CREATE TABLE UTENTI(
	USERNAME VARCHAR2(20) PRIMARY KEY,
	PASSWORD VARCHAR2(10),
	NOME VARCHAR2(50),
	COGNOME VARCHAR2(50),
	EMAIL VARCHAR2(30));

CREATE TABLE PRENOTAZIONI(
	CODICE NUMBER(7) PRIMARY KEY,
	USERNAME VARCHAR2(20),
	GIORNO DATE,
	ORARIO CHAR(5),
	NUMERO NUMBER(2),
	NOME VARCHAR2(50),
	CITTA VARCHAR2(50),
	FOREIGN KEY (NOME,CITTA,NUMERO,GIORNO,ORARIO) REFERENCES PALINSESTI (NOME, CITTA, NUMERO, GIORNO, ORARIO),
	FOREIGN KEY (USERNAME) REFERENCES UTENTI (USERNAME));

CREATE TABLE POSTI(
	RIGA NUMBER(2),
	COLONNA NUMBER(2),
	NUMERO NUMBER(2),
	NOME VARCHAR2(50),
	CITTA VARCHAR2(50),
	PREZZO NUMBER(5),
	CODICE NUMBER(7) UNIQUE,
	PRIMARY KEY (COLONNA, RIGA, NUMERO, NOME, CITTA),
	FOREIGN KEY (NUMERO, NOME, CITTA) REFERENCES SALE (NUMERO, NOME, CITTA),
	FOREIGN KEY (CODICE) REFERENCES PRENOTAZIONI (CODICE));

ALTER TABLE CINEMA
ADD UNIQUE (RECAPITO);

ALTER TABLE PRENOTAZIONI
ADD UNIQUE (USERNAME);

ALTER TABLE UTENTI
ADD UNIQUE (EMAIL);

