CREATE VIEW PALINSESTO_MALYGOS (GIORNO, ORARIO, NUMERO, NOME, CITTA, PREZZO, TITOLO) AS
SELECT P.GIORNO, P.ORARIO, P.NUMERO, P.NOME, P.CITTA, P.PREZZO, P.TITOLO
FROM PALINSESTI P
WHERE (P.GIORNO BETWEEN SYSDATE AND SYSDATE + 7) AND P.NOME = 'Malygos';

CREATE VIEW VISTA_PALINSESTI (GIORNO, ORARIO, NUMERO, NOME, CITTA, PREZZO, TITOLO) AS
SELECT GIORNO, ORARIO, NUMERO, NOME, CITTA, PREZZO, TITOLO
FROM PALINSESTI
WHERE GIORNO BETWEEN SYSDATE AND (SYSDATE + 7);

CREATE VIEW PRENOTAZIONI_OGGI_MALYGOS (CODICE, ORARIO, NUMERO) AS
SELECT CODICE, ORARIO, NUMERO
FROM PRENOTAZIONI
WHERE (GIORNO BETWEEN (SYSDATE - 1) AND (SYSDATE + 1)) AND NOME = 'Malygos';

CREATE VIEW PRENOTAZIONI_UTENTE_STE (CODICE, ORARIO, CITTA, GIORNO, NOME) AS
SELECT P.CODICE, P.ORARIO, P.CITTA, P.GIORNO, P.NOME
FROM PRENOTAZIONI P
WHERE P.USERNAME = 'Ste';